#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# Source environment settings
source "$DOTZSH/env.zsh"

# Customize to your needs...

export HOMEBREW_GITHUB_API_TOKEN=`(/usr/bin/security 2>&1 >/dev/null find-generic-password -a nickwright80@gmail.com -s "github_access_token" -g) | sed -e "s/^password: //" | tr -d '"'`